### ISSUE TITLE
Talkgroup numbers instead of names

### ISSUE THREAD

**Issue by DC7IA** [markuslindenberg/gencp#2]
I would like to suggest using only the numbers of the talkgroups instead of the names for channels.

Many channel names are too long for the display of the radio and this will result in shortened versions. But they names would still be very long, so that the text scrolls over the screen all the time. It would be easier to figure out what TG is being by simply using the number.

"262 DB0DDS" instead of "Germany DB0DDS"
and 
"26223 DB0DDS" instead of "Chaoswe DB0DDS"

Or maybe just "262 DDS"  and the zone will be named DB0DDS then..?

**Comment by markuslindenberg** [comment]
I changed this, maybe the names will optionally come back some day. 

I want the tool to work universally, so for now I don't want to add any magic/processing containing knowledge about certain countries (like that repeaters in DL start with DB0 so the DB0 can be stripped for brevity). Maybe that will be added later in a generic way.
